Fix a compiler error recently introduced in NotePixmapParameters.h : NotePixmapParameters.h:135: erreur: ‘fabs’ was not declared in this scope
git-svn-id: http://svn.code.sf.net/p/rosegarden/code/trunk/rosegarden@11650 cf6a83e7-f017-4305-b0b3-678bde24f230